### ISSUE TITLE
[PE-D] Incorrect example output for `searchmap 4`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-2/tp#195]
Based on the UG, the output for this command is as follows:

![image.png](https://raw.githubusercontent.com/Kair0s3/ped/main/files/fad3727b-3780-448f-b5f5-359525589859.png)

However, based on testing the application, the output was instead as follows:

![image.png](https://raw.githubusercontent.com/Kair0s3/ped/main/files/f3d1d96f-5c9b-426c-aedc-b6e6aaf9fd39.png)

This mismatch in the expected output may confuse the both readers and the users in this case, who are referring to the UG to test out the application. This would cause inconvenience for the users trying to figure out the application based on the UG. 

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Kair0s3/ped#3

**Comment by MAZJ124** [comment]
Add previous command to add in selected module in UG
