### ISSUE TITLE
[PE-D] Bug in adding a map after file permission altering 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-2/tp#197]
I have change the data directory to chmod 000 in which the program cannot access the data directory.

First, I will brute force and add uni 4

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/537d8db1-c02a-4a06-baca-e78c1b9581c9.png)

Next, I will add CS1231 which has mapping to uni 4

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/7977b22b-1ab2-4a85-b629-4d78941c4b53.png)

After which I will add the map.

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/98682982-10db-497c-b708-35eb7f5cb84a.png)

It can be seen that although the file cannot be access but the data object within the program went haywire. Map{4,2} exists and does not exists at the same time. I understand if it just cannot add to the text file but why does the map exists and no exists at the same time.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Woolicious98/ped#13

**Comment by titustortoiseturtle1999** [comment]
Invallid.
