### ISSUE TITLE
[PE-D] Vague error message from loading unreadable files

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-2/tp#199]
I have changed the data directory such that no program can access it using the chmod 000.

The error is handled but error message only display:

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/e7d36946-198d-400c-ab5b-252a0d06056b.png)

Perhaps could state that data directory is inaccessible. Or the file it is accessing is not accessible.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Woolicious98/ped#14

**Comment by titustortoiseturtle1999** [comment]
Invalid
