### ISSUE TITLE
[PE-D] Adding wrong mapping using text data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-2/tp#213]
Step 1: edit the text file

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/f73653e1-22b3-4e6c-ba48-a71d2d65b22e.png)

Step 2: 

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/1ce4074d-9681-4a8a-b2b2-ebf8b127be4e.png)

Step 3:

![image.png](https://raw.githubusercontent.com/Woolicious98/ped/main/files/20961675-8f53-41ad-a51b-530f97b6740d.png)

As seen it is treated as valid.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: Woolicious98/ped#18

**Comment by madhanse** [comment]
Issue solved
