### ISSUE TITLE
[PE-D] Module mapping is not removed after a module is removed from the module list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T09-2/tp#214]
#### Issue description

After a module is removed from the module list, the corresponding module mapping is not removed

#### Steps to reproduce the issue

1.  Remove a module from partner university that has been mapped to one of NUS module
2.  List the stored university list

#### What's the expected result?

- The module mapping corresponding with removed module should be removed

#### What's the actual result?

- The corresponding module mapping exists after the module is removed. In this case, CM4242 is still shown in module mapping despite being removed from the list.

#### Additional details / screenshot

![image.png](https://raw.githubusercontent.com/NonRNP/ped/main/files/1a436c0e-5568-41bb-9798-3029561b52b3.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: NonRNP/ped#5

**Comment by titustortoiseturtle1999** [comment]
It's a feature not a bug. Will add note in UG.
